---
- hosts: webservers
  become: yes
  tasks:
    - name: Deploy war to tomcat
      copy:
        src: /var/lib/jenkins/workspace/ansible/target/*.war
        dest: /opt/apache-tomcat-8.5.57/webapps
